# Generated by Django 5.0.7 on 2024-08-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_author_last_name_alter_book_isbn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstance",
            old_name="imprint",
            new_name="book_lender_uid",
        ),
    ]
