# Generated by Django 5.0.7 on 2024-08-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_imprint_bookinstance_book_lender_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text='13 Character (Input NA if not applicable) <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                verbose_name="ISBN",
            ),
        ),
    ]
